name: CI for Integration Service ROS 1 SystemHandle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  ros1-sh_CI:
    runs-on: ubuntu-20.04
    container: ros:noetic

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/ros1-sh

      - name: Download required dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y cmake gcc g++ git libboost-dev libboost-program-options-dev libyaml-cpp-dev python3-pip
          pip3 install colcon-common-extensions

      - name: Download the Integration Service
        run: |
          git clone --recursive https://github.com/eProsima/Integration-Service src/integration-service

      - name: Build
        run: |
          . /opt/ros/noetic/setup.sh
          colcon build --cmake-args -DBUILD_ROS1_TESTS=ON --event-handlers console_direct+

      - name: Test
        run: |
          . /opt/ros/noetic/setup.sh && . install/local_setup.sh
          roscore & colcon test --packages-up-to is-ros1-test --event-handlers console_direct+
          colcon test-result
